# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 79596dacba54dfa85851ef2ff09c4e49bbe232ffea8b4c272ff0303615e83402ce31166e43431d0bbabdeaa8e3b312f281435a64278cbdddf2534e58e2cf3312

test:
  secret_key_base: 4037643b904c67c67f26212351071f513b3c528fb394c7a2878892ff4ee23eca500668900ebcdc28801302e8ec88f987288f610575d0ccf13e60a5911695f22f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
